<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 3.3.9 setup script by Piotr Przybylski <piotrprz@gmail.com>
 * Date: Mon, 31 Jan 2011 11:10:45 -0500
 */

/* Servers configuration */
$i = 0;

/* Server: mysql01.unity.ncsu.edu [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = '';
$cfg['Servers'][$i]['host'] = 'mysql01.unity.ncsu.edu';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '';

/* End of servers configuration */

$cfg['blowfish_secret'] = '4d46defc76d2b2.56020186';
$cfg['DefaultLang'] = 'en-utf-8';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>